// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd3MnEoN43GP7yQuErNuEVzHAWX0_hsgE',
    appId: '1:884839819537:web:69d09d61871d929c3dc4b0',
    messagingSenderId: '884839819537',
    projectId: 'flutter-notes-app-c10de',
    authDomain: 'flutter-notes-app-c10de.firebaseapp.com',
    storageBucket: 'flutter-notes-app-c10de.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmdjGJfy-GoI2al2aYaipxJDufDAXuGm4',
    appId: '1:884839819537:android:39545fe0e9d893ee3dc4b0',
    messagingSenderId: '884839819537',
    projectId: 'flutter-notes-app-c10de',
    storageBucket: 'flutter-notes-app-c10de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9IMxrwFJ8IHjBPgTaNo8E_0BeQkSwwKU',
    appId: '1:884839819537:ios:abefbfe74fb8750b3dc4b0',
    messagingSenderId: '884839819537',
    projectId: 'flutter-notes-app-c10de',
    storageBucket: 'flutter-notes-app-c10de.firebasestorage.app',
    iosBundleId: 'com.example.firebaseauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9IMxrwFJ8IHjBPgTaNo8E_0BeQkSwwKU',
    appId: '1:884839819537:ios:abefbfe74fb8750b3dc4b0',
    messagingSenderId: '884839819537',
    projectId: 'flutter-notes-app-c10de',
    storageBucket: 'flutter-notes-app-c10de.firebasestorage.app',
    iosBundleId: 'com.example.firebaseauth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd3MnEoN43GP7yQuErNuEVzHAWX0_hsgE',
    appId: '1:884839819537:web:1d7ecedf2c28e6653dc4b0',
    messagingSenderId: '884839819537',
    projectId: 'flutter-notes-app-c10de',
    authDomain: 'flutter-notes-app-c10de.firebaseapp.com',
    storageBucket: 'flutter-notes-app-c10de.firebasestorage.app',
  );
}
